apiVersion: v1
kind: PersistentVolume
metadata:
  name: triton-model-repo
  labels:
    type: local
spec:
  storageClassName: rook-ceph-block
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/nirmalthomas/Desktop/CMS/sonic-models/kube-depl/"