apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-triton-ragged
  namespace: cms-ml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-triton-ragged
  template:
    metadata:
      labels:
        app: server-triton-ragged
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nvidia.com/gpu.product
                operator: In
                values:
                - NVIDIA-GeForce-GTX-1080-Ti
                - NVIDIA-GeForce-GTX-2080-Ti
      # tolerations:
      # - key: "nautilus.io/large-gpu"
      #   operator: "Exists"
      #   effect: "NoSchedule"
      containers:
      - name: triton
        # image: nvcr.io/nvidia/tritonserver:21.03-py3
        image: nvcr.io/nvidia/tritonserver:22.03-py3
        command: ["bash", "-c"]
        args: ["git clone https://github.com/nirmalthomas2609/sonic-models.git -b temp /triton/sonic-models-ragged && tritonserver --model-repository=/triton/sonic-models-ragged/models --exit-on-error=true"]
        stdin: true
        tty: true
        ports:
        - name: http
          containerPort: 8000
          protocol: TCP
        - name: grpc
          containerPort: 8001
          protocol: TCP
        - name: metrics
          containerPort: 8002
          protocol: TCP
        resources:
          limits:
            memory: 4Gi
            cpu: "1"
            nvidia.com/gpu: "1"
          requests:
            memory: 4Gi
            cpu: "1"
            nvidia.com/gpu: "1"
        volumeMounts:
        - mountPath: /triton
          name: triton-model-repository
      volumes:
      - name: triton-model-repository
        persistentVolumeClaim:
          claimName: triton-model-repository
