apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: triton-model-repository
  namespace: triton
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
